/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package views;

import controller.Laberinto;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import views.tablas.ModeloTablaLaberinto;
import java.awt.Color;
import java.awt.Component;
import java.awt.Font;

/**
 *
 * @author alexa
 */
public class FrmLaberinto extends javax.swing.JDialog {

    private ModeloTablaLaberinto mtl = new ModeloTablaLaberinto();
    private Laberinto l = new Laberinto();

    public FrmLaberinto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        // pintar_tabla();
    }

    private void pintar_tabla() {

        tbllaberinto.setDefaultRenderer(Object.class, new LaberintoRenderer());
        tbllaberinto.setRowHeight(20);
        tbllaberinto.setShowGrid(true);
        tbllaberinto.setGridColor(Color.GREEN);
        tbllaberinto.setEnabled(false);
        tbllaberinto.setRowSelectionAllowed(false);
        tbllaberinto.setColumnSelectionAllowed(false);
        tbllaberinto.setTableHeader(null);
    }

    private void generar_laberinto() {
        try {
            int dimension = (Integer) spndimension.getValue();
            String[][] datos = l.generarLaberinto(dimension);
            if (datos == null) {
                JOptionPane.showMessageDialog(this,
                        "Error al generar el laberinto",
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
                return;
            } else {
                mtl.setLaberinto(datos);
                tbllaberinto.setModel(mtl);

            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,
                    "Error inesperado: " + ex.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    private void limpiar() {
        try {
            mtl.setLaberinto(new String[0][0]);
            tbllaberinto.setModel(mtl);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,
                    "Error al limpiar la tabla: " + ex.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    private class LaberintoRenderer extends DefaultTableCellRenderer {

        public Component getTableCellRendererComponent(JTable table, Object value,
                boolean isSelected, boolean hasFocus, int row, int column) {
            Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
            setHorizontalAlignment(CENTER);
            c.setFont(new Font("Laberinto", Font.BOLD, 12));
            if (value != null) {
                String celda = value.toString();
                switch (celda) {
                    case "": //Muro
                        c.setBackground(Color.BLACK);
                        c.setForeground(Color.BLACK);
                        break;
                    case " ": //Camino libre 
                        c.setBackground(Color.white);
                        c.setForeground(Color.BLACK);

                        break;
                    case "I": //Entrada
                        c.setBackground(Color.GREEN);
                        c.setForeground(Color.WHITE);
                        break;
                    case "F": //Salida
                        c.setBackground(Color.RED);
                        c.setForeground(Color.WHITE);
                        break;
                    default:
                        c.setBackground(Color.BLACK);
                        c.setForeground(Color.BLACK);
                }
            } else {
                c.setBackground(Color.black);
                c.setForeground(Color.BLACK);
            }
            return c;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btngenerar = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();
        spndimension = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbllaberinto = new javax.swing.JTable();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Datos de laberinto", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 14), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(0, 51, 51));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Dimensiones:");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(160, 40, 100, 30);

        btngenerar.setBackground(new java.awt.Color(255, 255, 255));
        btngenerar.setForeground(new java.awt.Color(0, 0, 0));
        btngenerar.setText("GENERAR");
        btngenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngenerarActionPerformed(evt);
            }
        });
        jPanel2.add(btngenerar);
        btngenerar.setBounds(170, 90, 90, 27);

        btncancelar.setBackground(new java.awt.Color(255, 255, 255));
        btncancelar.setForeground(new java.awt.Color(0, 0, 0));
        btncancelar.setText("CANCELAR");
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });
        jPanel2.add(btncancelar);
        btncancelar.setBounds(340, 90, 100, 27);

        spndimension.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        spndimension.setModel(new javax.swing.SpinnerNumberModel(10, 10, 100, 1));
        jPanel2.add(spndimension);
        spndimension.setBounds(290, 40, 120, 30);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 10, 640, 150);

        tbllaberinto.setBackground(new java.awt.Color(255, 255, 255));
        tbllaberinto.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tbllaberinto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbllaberinto);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 170, 640, 500);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 660, 710);

        setSize(new java.awt.Dimension(678, 718));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btngenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngenerarActionPerformed
        generar_laberinto();
    }//GEN-LAST:event_btngenerarActionPerformed

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        limpiar();
    }//GEN-LAST:event_btncancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLaberinto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLaberinto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLaberinto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLaberinto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmLaberinto dialog = new FrmLaberinto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btngenerar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner spndimension;
    private javax.swing.JTable tbllaberinto;
    // End of variables declaration//GEN-END:variables
}
