/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package views;

import controller.Usuario;
import javax.swing.JOptionPane;
import views.tablas.ModeloTablaUsuario;

/**
 *
 * @author alexa
 */
public class FrmUsuario extends javax.swing.JDialog {
    private ModeloTablaUsuario mtu = new ModeloTablaUsuario();
    private Usuario s = new Usuario();
    private Integer[][] matriz;

    public FrmUsuario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        tbltabla.setModel(mtu);
    }

    private void cargar_tabla() {
        try {
            int filas = ((Integer) spnfilas.getValue()).intValue();
            int columnas = ((Integer) spncolumnas.getValue()).intValue();
            matriz = s.crearMatriz(filas, columnas);
            if (matriz != null) {
                mtu.setDatos(matriz, filas, columnas);
           
                mtu.fireTableStructureChanged();
            } else {
                JOptionPane.showMessageDialog(this,
                        "Error al crear la matriz.",
                        "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,
                    "Error al cargar la tabla: " + ex.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }

      private void eliminarNum() {
        if (matriz == null) {
            JOptionPane.showMessageDialog(null, "Primero debe crear una matriz.");
            return;
        }
        try {
            int numero = Integer.parseInt(txteliminar.getText());
            if (s.eliminarNumero(numero, matriz)) {
                mtu.setDatos(matriz, matriz.length, matriz[0].length);
                JOptionPane.showMessageDialog(null, "Numero ingresado, eliminado correctamente");
                txteliminar.setText("");
            } else {
                JOptionPane.showMessageDialog(null, "El numero " + numero + " no se encuentra en la matriz :0 " + "\n" + "Intente de nuevo ");
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Ingrese un número válido");
        }
    }

    private void eliminarPrimos() {
        if (matriz == null || matriz.length == 0) {
            JOptionPane.showMessageDialog(null, "Primero debe crear una matriz.");
            return;
        }
        s.setMatriz(matriz);
        int contPrimos = s.nrPrimos();
        if (contPrimos == 0) {
            JOptionPane.showMessageDialog(null, "No se encontraron números primos en la matriz.");
            return;
        }else{
        s.eliminarNumerosPrimos();
        mtu.setDatos(matriz, matriz.length, matriz[0].length);
        JOptionPane.showMessageDialog(null, "Se eliminaron " + contPrimos + " números primos correctamente.");
        
    }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btncrear = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        spnfilas = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        spncolumnas = new javax.swing.JSpinner();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txteliminar = new javax.swing.JTextField();
        btnaceptar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnprimos = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbltabla = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "DATOS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel2.setLayout(null);

        btncrear.setBackground(new java.awt.Color(0, 51, 51));
        btncrear.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btncrear.setText("CREAR MATRIZ");
        btncrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncrearActionPerformed(evt);
            }
        });
        jPanel2.add(btncrear);
        btncrear.setBounds(160, 100, 280, 31);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Nro de Filas: ");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(30, 50, 100, 20);

        spnfilas.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));
        jPanel2.add(spnfilas);
        spnfilas.setBounds(140, 50, 68, 26);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nro de Columnas:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(330, 50, 130, 20);

        spncolumnas.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));
        jPanel2.add(spncolumnas);
        spncolumnas.setBounds(470, 50, 68, 26);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 10, 600, 160);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Mostrar Matriz", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel3.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Eliminar numero:");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(50, 270, 130, 20);
        jPanel3.add(txteliminar);
        txteliminar.setBounds(190, 270, 180, 26);

        btnaceptar.setBackground(new java.awt.Color(51, 51, 51));
        btnaceptar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnaceptar.setForeground(new java.awt.Color(0, 255, 255));
        btnaceptar.setText("ACEPTAR");
        btnaceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaceptarActionPerformed(evt);
            }
        });
        jPanel3.add(btnaceptar);
        btnaceptar.setBounds(410, 270, 120, 31);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Eliminar Numeros Primos:");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(50, 330, 190, 20);

        btnprimos.setBackground(new java.awt.Color(51, 51, 51));
        btnprimos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnprimos.setForeground(new java.awt.Color(0, 255, 255));
        btnprimos.setText("DELETE");
        btnprimos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprimosActionPerformed(evt);
            }
        });
        jPanel3.add(btnprimos);
        btnprimos.setBounds(250, 330, 120, 31);

        tbltabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tbltabla);

        jPanel3.add(jScrollPane2);
        jScrollPane2.setBounds(50, 30, 490, 220);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(20, 180, 590, 440);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 620, 660);

        setSize(new java.awt.Dimension(637, 666));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btncrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncrearActionPerformed
        cargar_tabla();
    }//GEN-LAST:event_btncrearActionPerformed

    private void btnaceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaceptarActionPerformed
        eliminarNum();
    }//GEN-LAST:event_btnaceptarActionPerformed

    private void btnprimosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprimosActionPerformed
        eliminarPrimos();
    }//GEN-LAST:event_btnprimosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmUsuario dialog = new FrmUsuario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnaceptar;
    private javax.swing.JButton btncrear;
    private javax.swing.JButton btnprimos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner spncolumnas;
    private javax.swing.JSpinner spnfilas;
    private javax.swing.JTable tbltabla;
    private javax.swing.JTextField txteliminar;
    // End of variables declaration//GEN-END:variables
}
